//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OilfieldCalc3.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OilfieldCalc3.Resx.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of this calculator can help with daily drilling operational calculations on a drilling rig. This program will also aide in required calculations needed for critical well control operations. Please remember that this software is provided for reference only and is no substitution for Experience and expertise in the event that a well control situation has occured..
        /// </summary>
        internal static string AboutMessage {
            get {
                return ResourceManager.GetString("AboutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2020 BWE Inc..
        /// </summary>
        internal static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oilfield Calculator 3.0.0.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drillstring Details.
        /// </summary>
        internal static string DrillstringDetailPageTitle {
            get {
                return ResourceManager.GetString("DrillstringDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drillstring Tubulars.
        /// </summary>
        internal static string DrillstringPageTitle {
            get {
                return ResourceManager.GetString("DrillstringPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditString {
            get {
                return ResourceManager.GetString("EditString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MainPageTitle {
            get {
                return ResourceManager.GetString("MainPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drillstring.
        /// </summary>
        internal static string MenuItemDrillstring {
            get {
                return ResourceManager.GetString("MenuItemDrillstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string MenuItemMain {
            get {
                return ResourceManager.GetString("MenuItemMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string MenuItemSettings {
            get {
                return ResourceManager.GetString("MenuItemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumes.
        /// </summary>
        internal static string MenuItemVolumes {
            get {
                return ResourceManager.GetString("MenuItemVolumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbore.
        /// </summary>
        internal static string MenuItemWellbore {
            get {
                return ResourceManager.GetString("MenuItemWellbore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuTitle {
            get {
                return ResourceManager.GetString("MenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsPageTitle {
            get {
                return ResourceManager.GetString("SettingsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SettingsTabAboutTitle {
            get {
                return ResourceManager.GetString("SettingsTabAboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Settings.
        /// </summary>
        internal static string SettingsTabAdvancedTitle {
            get {
                return ResourceManager.GetString("SettingsTabAdvancedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units of Measure.
        /// </summary>
        internal static string SettingsTabUnitsTitle {
            get {
                return ResourceManager.GetString("SettingsTabUnitsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Settings.
        /// </summary>
        internal static string SettingsTabUserTitle {
            get {
                return ResourceManager.GetString("SettingsTabUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string String_Add {
            get {
                return ResourceManager.GetString("String_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjusted Weight.
        /// </summary>
        internal static string String_AdjustedWieght {
            get {
                return ResourceManager.GetString("String_AdjustedWieght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Administrator Options.
        /// </summary>
        internal static string String_AdminOptions {
            get {
                return ResourceManager.GetString("String_AdminOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capaity Unit.
        /// </summary>
        internal static string String_CapacityUnit {
            get {
                return ResourceManager.GetString("String_CapacityUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string String_Capacty {
            get {
                return ResourceManager.GetString("String_Capacty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Data.
        /// </summary>
        internal static string String_ClearData {
            get {
                return ResourceManager.GetString("String_ClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Drillstring Database.
        /// </summary>
        internal static string String_ClearDrillstring_Checkbox {
            get {
                return ResourceManager.GetString("String_ClearDrillstring_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear User Settings.
        /// </summary>
        internal static string String_ClearSettings_Checkbox {
            get {
                return ResourceManager.GetString("String_ClearSettings_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Wellbore Database.
        /// </summary>
        internal static string String_ClearWellbore_Checkbox {
            get {
                return ResourceManager.GetString("String_ClearWellbore_Checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Options.
        /// </summary>
        internal static string String_ColorOptions {
            get {
                return ResourceManager.GetString("String_ColorOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Controls.
        /// </summary>
        internal static string String_DatabaseOptions {
            get {
                return ResourceManager.GetString("String_DatabaseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        internal static string String_Displacement {
            get {
                return ResourceManager.GetString("String_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside Diameter.
        /// </summary>
        internal static string String_InsideDiameter {
            get {
                return ResourceManager.GetString("String_InsideDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Length Unit.
        /// </summary>
        internal static string String_LongLengthUnit {
            get {
                return ResourceManager.GetString("String_LongLengthUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mass Unit.
        /// </summary>
        internal static string String_MassUnit {
            get {
                return ResourceManager.GetString("String_MassUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OD.
        /// </summary>
        internal static string String_OD {
            get {
                return ResourceManager.GetString("String_OD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside Diameter.
        /// </summary>
        internal static string String_OutsideDiameter {
            get {
                return ResourceManager.GetString("String_OutsideDiameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Length Unit.
        /// </summary>
        internal static string String_ShortLengthUnit {
            get {
                return ResourceManager.GetString("String_ShortLengthUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Capacity.
        /// </summary>
        internal static string String_TotalCapacity {
            get {
                return ResourceManager.GetString("String_TotalCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Disp.
        /// </summary>
        internal static string String_TotalDisplacement {
            get {
                return ResourceManager.GetString("String_TotalDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Length.
        /// </summary>
        internal static string String_TotalLength {
            get {
                return ResourceManager.GetString("String_TotalLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Weight.
        /// </summary>
        internal static string String_TotalWeight {
            get {
                return ResourceManager.GetString("String_TotalWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Selectable Units.
        /// </summary>
        internal static string String_UnitOptions {
            get {
                return ResourceManager.GetString("String_UnitOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Dark Mode.
        /// </summary>
        internal static string String_UseDarkMode {
            get {
                return ResourceManager.GetString("String_UseDarkMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        internal static string String_Volume {
            get {
                return ResourceManager.GetString("String_Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume Unit.
        /// </summary>
        internal static string String_VolumeUnit {
            get {
                return ResourceManager.GetString("String_VolumeUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose application theme.
        /// </summary>
        internal static string ThemePickerTitle {
            get {
                return ResourceManager.GetString("ThemePickerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbore Details.
        /// </summary>
        internal static string WellboreDetailPageTitle {
            get {
                return ResourceManager.GetString("WellboreDetailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wellbore Tubulars.
        /// </summary>
        internal static string WellborePageTitle {
            get {
                return ResourceManager.GetString("WellborePageTitle", resourceCulture);
            }
        }
    }
}
